// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbvkhxqjjirlifxfnizb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtidmtoeHFqamlybGlmeGZuaXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTcwMTMsImV4cCI6MjA2NzI3MzAxM30.s29rzauwEuqhxiGTpLoqT6r0NnVKfqlLpqbj0-RXFcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});